# example netlify.toml
[build]
  command = "next build"
  functions = "functions"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/next_api_sitemap"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/.netlify/functions/next_api_robots"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
